# Uncomment the next line to define a global platform for your project
platform :ios, '15.6'

target 'BabyTracker2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BabyTracker2
  
  # Networking
  pod 'Alamofire', '5.4.0'  # HTTP networking library
  
  # UI Components
  # pod 'Charts', '3.5.0'     # Beautiful charts for iOS - 暫時禁用
  
  # KeychainSwift已移除，將使用原生API替代
end
